services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-health-tracker-app
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy

    environment:
      TZ: Europe/Moscow
      JAVA_TOOL_OPTIONS: ${JAVA_TOOL_OPTIONS}

      APP_PORT: 8081

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_LIQUIBASE_ENABLED: "true"

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}

      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS: ${MAIL_SMTP_STARTTLS}
      MAIL_SMTP_SSL: ${MAIL_SMTP_SSL}
      MAIL_FROM: ${MAIL_FROM}

      TELEGRAM_API_URL: ${TELEGRAM_API_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_BINDING_TOKEN_EXPIRATION_MINUTES: ${TELEGRAM_BINDING_TOKEN_EXPIRATION_MINUTES}

      VK_API_URL: ${VK_API_URL}
      VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN}
      VK_API_VERSION: ${VK_API_VERSION}
      VK_GROUP_ID: ${VK_GROUP_ID}
      VK_CONFIRMATION_CODE: ${VK_CONFIRMATION_CODE}
      VK_CALLBACK_SECRET: ${VK_CALLBACK_SECRET}

      PASSWORD_RESET_LOG_TOKEN: ${PASSWORD_RESET_LOG_TOKEN}

      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: node-health-tracker-frontend
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "${FRONTEND_PORT}:80"

  db:
    image: postgres:17
    container_name: node-health-tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data_prod:
