app:
  build: .
  container_name: network-services-app
  depends_on:
    db:
      condition: service_healthy
    mailpit:
      condition: service_started
  environment:
    TZ: Europe/Moscow
    JAVA_TOOL_OPTIONS: -Duser.timezone=Europe/Moscow

    SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
    SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
    SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    SPRING_LIQUIBASE_ENABLED: "true"

    JWT_SECRET: ${JWT_SECRET}
    JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}

    MAIL_HOST: ${MAIL_HOST}
    MAIL_PORT: ${MAIL_PORT}
    MAIL_USERNAME: ${MAIL_USERNAME}
    MAIL_PASSWORD: ${MAIL_PASSWORD}
    MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
    MAIL_SMTP_STARTTLS: ${MAIL_SMTP_STARTTLS}
    MAIL_FROM: ${MAIL_FROM}
    MAIL_SMTP_SSL: ${MAIL_SMTP_SSL}

    TELEGRAM_API_URL: ${TELEGRAM_API_URL}
    TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}

    VK_API_URL: ${VK_API_URL}
    VK_ACCESS_TOKEN: ${VK_ACCESS_TOKEN}
    VK_API_VERSION: ${VK_API_VERSION}
    VK_GROUP_ID: ${VK_GROUP_ID}
    VK_CONFIRMATION_CODE: ${VK_CONFIRMATION_CODE}
    VK_CALLBACK_SECRET: ${VK_CALLBACK_SECRET}

    PASSWORD_RESET_LOG_TOKEN: ${PASSWORD_RESET_LOG_TOKEN}
  ports:
    - "${APP_PORT}:8081"