spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

server:
  port: ${APP_PORT:8081}

app:
  monitoring:
    scheduler:
      enabled: true
      fixed-delay-ms: 10000